- asyncio_mqtt/client.py
The client works great for me, I love how intuitive it is to use. Since my mqtt server requires authentication and I saw no builtin way to use it I added it this way to the client startup.
In paho one calls _client.set_username_pw after the client is instantiated but with the context manager setting up the context fails. Because one never enterst the context one never gets a chance to pass the credentials to the client.
> Enable credential passing for client

- README.md
- asyncio_mqtt/client.py
When using `unfiltered_messages` to receive all MQTT messages it would be useful if information about the message was provided instead of just the payload. This PR changes the implementation to pass on the instance of MQTTMessage from paho instead of only the payload of the message.
Fixes #2.
> Pass received message information onward instead of only the payload

- asyncio_mqtt/client.py
In `e645297 feat: improve reconnection support (yet again)`, python3.6 got
broken because of a call to `asyncio.create_task`, which only exists in
python 3.7.  The fix is to replace it with `self._loop.create_task`.
Signed-off-by: Derrick Lyndon Pallas <derrick@meter.com>
> fix: python 3.6 compat in _message_generator

- asyncio_mqtt/client.py
Small fix adds "transport" option to the constructor.
This allows to use "websocket" transport layer instead of default "tcp".
> Added transport option to Client construnctor

- .gitignore
- asyncio_mqtt/client.py
- tests/reconnect.py
> Make connect() non-blocking

- asyncio_mqtt/client.py
I'm testing this library to use with Home Assistant. I've written a client based on the advanced example in the readme.
It seems we're setting an exception on the `self._disconnected` `asyncio.Future` used in `_on_disconnect`, even though the future is never awaited if there's an exception in the connect flow.
Without this fix, when the connection is refused, I'm seeing:
```
2020-11-27 01:20:49,138 INFO (MainThread) [openzwavemqtt] Starting client.
2020-11-27 01:20:49,138 DEBUG (MainThread) [asyncio] Using selector: EpollSelector
2020-11-27 01:20:49,147 DEBUG (ThreadPoolExecutor-0_0) [paho.mqtt.client] Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b'6SHLIyeUtZENAYM3p4xxFi'
2020-11-27 01:20:49,150 DEBUG (MainThread) [paho.mqtt.client] Received CONNACK (0, 5)
2020-11-27 …
```
> Fix future exception on disconnect

- asyncio_mqtt/client.py
Fixing the following error:
```
File /venv/lib/python3.8/site-packages/asyncio_mqtt/client.py", line 81, in connect
self._client.socket().setsockopt(socket.SOL_SOCKET, socket.SO_SNDBUF, 2048)
AttributeError: 'WebsocketWrapper' object has no attribute 'setsockopt'
```
> Fix socket options for websocket transport

- asyncio_mqtt/__init__.py
Stops mypy from complaining about the imports in `__init__.py` not being explicitly reexported.
https://mypy.readthedocs.io/en/stable/config_file.html#confval-implicit_reexport
> Add explicit export __all__ in __init__.py

- asyncio_mqtt/client.py
In #39 there's a second exception caused by `self._mqtt_task` being `None` when we try to cancel it. Since it's initialised as `None`, we shouldn't assume that it's not.
This is also something that would need to be fixed once type hints are added.
> Check that _misc_task is not None before trying to cancel it.

- asyncio_mqtt/client.py
> Create _misc_loop() task thread safely. Fixes #39

- asyncio_mqtt/client.py
- asyncio_mqtt/error.py
- asyncio_mqtt/version.py
- setup.py
- tests/reconnect.py
Just an example of what would change, as mentioned in #37 
I personally use a line length of 90, but it makes no difference to me to use a different one.
> Format code with black

- asyncio_mqtt/client.py
After latest refactor websocket transport is broken again
> Fix client socket defaults for websocket transport

- asyncio_mqtt/client.py
The MQTTv5 protocol no longer uses `clean_session` setting of the client - it's prohibited by the underlying client to even set this argument when using MQTTv5 protocol. Instead, the MQTTv5 has a `clean_start` argument which has to be passed to the `connect` method of the client.
The asyncio-mqtt `Client` class doesn't provide any way to pass extra arguments to underlying client's `connect` method. This prevents using (amongst other) the clean_start functionality with MQTTv5 protocol.
This PR proposes a way to set arguments for the underlying paho client connect method, including the `clean_start` one, by providing a `ConnectArgs` class containing all the extra args and adds an optional `connect_args` argument to `Client` constructor.
An example usage:
```python
async def main():
async …
```
> Add ability to pass arguments to underlying client's connect method.

- asyncio_mqtt/client.py
- tests/reconnect.py
The library currently uses methods like ```get_running_loop()```, which are only available in python>=3.7
This PR fixes that.
Fixes the downstream-issue https://github.com/flyte/mqtt-io/issues/192
> Fix python3.6 compatibility

- asyncio_mqtt/error.py
> handle rc ReasonCodes

- asyncio_mqtt/client.py
Remove Asyncio loop reader for a socket, when its file number is valid as `socket.fileno` can return -1, see https://docs.python.org/3/library/socket.html#socket.socket.fileno.
This can happen because creation of socket can be delayed due to sleep  statements in Client._misc_loop method.
Also, cancel misc task only when it is not done.
> Improve cleanup when socket is invalid

- README.md
- asyncio_mqtt/__init__.py
- examples/EXAMPLES.md
docs: Added a Publisher example, how to handle with the Client arguments and added an example of how to deal with JSON data; included ProtocolVersion in the __init__.py so that we can directly summon the Enum from the package import
This addresses #63
> Publisher/Subscribe example also for JSON data and ProtocolVersion in the init

- asyncio_mqtt/client.py
I have a python script with this library subscribed to two topics on a self-hosted mosquitto broker. Rebooting the router between the two caused the script to crash with an `InvalidStateError` in `force_disconnect()` (full stack trace below).
I think this error happens because i have two coroutines with an `async for` waiting for messages from two separate `client.filtered_messages()`. One of them gets the error first and runs `__aexit__()` and ends up calling `force_disconnect()`. When the second one gets there, the `_disconnect` future already has a result and `set_result()` causes the `InvalidStateError`.
`__aexit__()` already has code to prevent this:
```
async def __aexit__(
self, exc_type: Type[Exception], exc: Exception, tb: TracebackType
) -> None:
"""Disconnect from the …
```
> avoid InvalidStateError on disconnect

- asyncio_mqtt/client.py
From https://github.com/sbtinstruments/asyncio-mqtt/issues/70 issue.
> Added a new parameter for configuring socket connection.

- asyncio_mqtt/client.py
- setup.py
While running the "advanced" example from the readme with pyright, i noticed it was alerting me to some typing issues, relating to asynccontextmanager and `Client.__aexit__`.
<details>
<summary>Pyright errors</summary>
```
Argument of type "Client" cannot be assigned to parameter "cm" of type "AsyncContextManager[_T@enter_async_context]" in function "enter_async_context"
"Client" is incompatible with protocol "AsyncContextManager[_T@enter_async_context]"
"__aexit__" is an incompatible type
Type "(exc_type: Type[Exception], exc: Exception, tb: TracebackType) -> Coroutine[Any, Any, None]" cannot be assigned to type "(__exc_type: Type[BaseException] | None, __exc_value: BaseException | None, __traceback: TracebackType | None) -> Awaitable[bool | None]"
Parameter 1: type "Type[BaseException] …
```
> Fix typing, mostly related to async_generator

- asyncio_mqtt/client.py
Pyright gets confused and will give you error messages like this:
```
error: Object of type "AsyncIterator[AsyncGenerator[...]]" cannot be used with "with" because it does not implement __aenter__ (reportGeneralTypeIssues)
error: Object of type "AsyncIterator[AsyncGenerator[...]]" cannot be used with "with" because it does not implement __aexit__ (reportGeneralTypeIssues)
```
For code like this:
```python
async with Client("test.mosquitto.org") as client:
async with client.filtered_messages("floors/+/humidity") as messages:
await client.subscribe("floors/#")
async for message in messages:
print(message.payload.decode())
```
This change statically checks against `sys.version_info` for the right version, which Pyright understands.
For additional discussion, see …
> Pyright reports false positive error with `asynccontextmanager`

- asyncio_mqtt/client.py
This PR applies a backpressure mechanism so that extremely chatty clients don't add congestion to the server. The mechanism is controlled with a `max_concurrent_outgoing_calls` parameter that can be applied to the client during instantiation:
* A `max_concurrent_outgoing_calls` value of `None` means that no back pressure is applied
* A `max_concurrent_outgoing_calls` value with a positive `int` indicates that no more than `max_concurrent_outgoing_calls` outgoing calls can happen at any given time.
Fixes https://github.com/sbtinstruments/asyncio-mqtt/issues/29
@frederikaalund Some comments for your review and consideration:
* As discussed, the fact that `max_concurrent_outgoing_calls` can be `None` (and is so by default) should retain backward compatibility.
* I didn't see any other spots …
> Add backpressure mechanism to limit the number of concurrent outgoing calls

- asyncio_mqtt/client.py
The `_on_socket_close` method can be called from a different thread than the
running event loop if an error occurs while the connection is being
established.  This can happen, for example, if the TCP connection is
established, but the TLS or WebSocket handshake fails.  It is not safe to
cancel the task from another thread.  Instead, the cancellation should be
scheduled to run as soon as the event loop is idle.
> client: Fix thread safety in socket close callback

- asyncio_mqtt/client.py
The `Client` constructor now takes two additional arguments:
`websocket_path` and `websocket_headers`.  These correspond to the
`path` and `headers` arguments of the underlying Paho
`Client.set_ws_options` method.  Users may need to specify these values,
depending on their environment configuration.
> client: Expose WebSocket connection options

- CHANGELOG.md
- asyncio_mqtt/client.py
This fixes https://github.com/sbtinstruments/asyncio-mqtt/issues/122
> Fix race conditions that may cause `InvalidStateError`.

- asyncio_mqtt/client.py
I use the comments about the design of adding `tls_set` to `asyncio-mqtt` from https://github.com/sbtinstruments/asyncio-mqtt/issues/14#issuecomment-671780413 and try to implement in the light of that. 
My implementation allows the use of a `TLSParameters` object to invoke `tls_set()` function of paho-mqtt client in asyncio-mqtt. Let me know if it makes sense. I would also like some pointers in regards to testing this
> use tls_set() in addition to tls_context

- README.md
- asyncio_mqtt/client.py
This commit adds the functionality of paho-mqtt's `proxy_set()` to asyncio-mqtt
> paho.mqtt.proxy_set() - support

- README.md
I just wanted to ask for improvements and suggestions when adding the recent changes to the README.md
If this is alright (for now, just tls_set example added) I can add the proxy settings as well
> Added documentation for tls_set in README.md

- README.md
The TLS configuration example in the README fails to run as is because the `ProtocolVersion` is not imported. I added that small change (line 153), relevant PR is #128. I also formatted the `README` with `Prettier` for some more consistency, I hope that's fine with you, otherwise, I'll revert it.
> Fix missing ProtocolVersion import in TLS configuration example

- README.md
`hbmqtt` is no longer maintained, there exists an active fork called `aqmtt`. I switched those two out and tried to simplify the list of alternatives by generalizing to "Related projects" not just `asyncio`-based. I removed `aiomqtt` as they recommend `asyncio-mqtt` themselves.
Let me know what you think 😊
-- Felix
> Update related projects list

- asyncio_mqtt/client.py
- setup.py
The signature of the `Client.subscibe()` for example only displayed
`(...) -> Coroutine[Any, Any, Tuple[int] | List[ReasonCodes]]` 
instead of
`(topic: str | Tuple[str, SubscribeOptions] | List[Tuple[str, SubscribeOptions]] | List[Tuple[str, int]], qos: int = ..., options: SubscribeOptions | None = ..., properties: Properties | None = ..., *args: Any, timeout: int = ..., **kwargs: Any) -> Coroutine[Any, Any, Tuple[int] | List[ReasonCodes]]`
> Fix autocomplete for _outgoing_call decorator

- README.md
Hi Frederik!
The _Advanced usage_ section may be a bit overwhelming at first sight. I was thinking about dissecting it into smaller sections/examples that each explains only a single concept e.g. _Reconnecting_ (see lines 41-56).
This makes it more in line with the TLS and Proxying sections and would make it easier to add/remove/edit the examples in the future. I'd also like to add a section about topic filters, closing #105.
Let me know what you think 😊
-- Felix
> Simplify and extend usage documentation

- README.md
Hi Frederik!
Again with the README 😄 I tweaked a few little things, and reordered the sections, among others to move the _Note for Windows users_ higher, as there are quite a few people who seem to overlook this. (Btw. is there anything that speaks against implementing the switch to the `SelectorEventLoop` directly in the code? I guess changing the loop silently is not a very nice pattern.)
~ Felix
> docs: reorder README sections in order of importance

- .github/workflows/test.yml
- .gitignore
- .pre-commit-config.yaml
- README.md
- asyncio_mqtt/client.py
- setup.py
- tests/conftest.py
- tests/test_client.py
Add tests and coverage for Continuous Integration.
> Add tests and coverage

- .flake8
- .pre-commit-config.yaml
- CONTRIBUTING.md
- asyncio_mqtt/client.py
- asyncio_mqtt/types.py
- pyproject.toml
- tests/test_client.py
- tests/test_error.py
[Ruff](https://github.com/charliermarsh/ruff) is the new `flake8` (near instant linting).
Check out the [launch blog article](https://notes.crmarsh.com/python-tooling-could-be-much-much-faster).
> Replace flake8 by ruff 🚀

- .github/workflows/test.yml
- CHANGELOG.md
- asyncio_mqtt/client.py
- tests/test_client.py
> Add pending calls threshold property

- CHANGELOG.md
- asyncio_mqtt/client.py
Client initializer currently accepts a logger as an optional argument. That logger is passed to the underlying paho.mqtt library and then used for logging there. However, there also exists MQTT_LOGGER, which is used internally by asyncio-mqtt. Without looking at the source code it is easy to forget that in order to enable logging both in paho.mqtt and in asyncio-mqtt it is not enough to pass a logger as an argument to Client initializer.
This PR makes asyncio-mqtt use a user-provided logger instead of MQTT_LOGGER for internal logging, so that if user decides to pass a logger to Client constructor, that logger will be used both in paho.mqtt and asyncio-mqtt.
> fix: consistently use a user-provided logger

- asyncio_mqtt/client.py
fixes #116
NOTE: `timeout` field of `Client._wait_for` has type `float` but default value all over code is `int`.
> Make default timeout configurable

- pyproject.toml
- tests/test_client.py
Multiple tests require network access, which prevents them from succeeding when running the tests in a sandboxed environment.
Setting up a marker allows skipping these in bulk, when necessary.
---
We're packaging aiomqtt in nixpkgs and always had to disable these tests. Would be awesome to share this marker upstream and let multiple distros reuse it.
The test summary without this fix:
```
aiomqtt> =========================== short test summary info ============================
aiomqtt> FAILED tests/test_client.py::test_multiple_messages_generators - aiomqtt.error.MqttError: [Errno -3] Temporary failure in name resolution
aiomqtt> FAILED tests/test_client.py::test_client_filtered_messages - aiomqtt.error.MqttError: [Errno -3] Temporary failure in name resolution
aiomqtt> FAILED …
```
> test: add network marker to tests

- .github/workflows/docs.yml
- CONTRIBUTING.md
- README.md
- aiomqtt/client.py
- docs/alongside-fastapi-and-co.md
- docs/conf.py
- docs/connecting-to-the-broker.md
- docs/developer-interface.md
- docs/index.md
- docs/introduction.md
- docs/subscribing-to-a-topic.md
- pyproject.toml
- scripts/README.md
- scripts/docs
I added Google-style docstrings to most of the classes to autogenerate a reference section in the docs (+ some smaller documentation tweaks). You can preview the docs as usual with `./scripts/setup && ./scripts/docs --reload`. Happy to hear what you think!
> Add reference section to docs

- aiomqtt/client.py
With #216 the "early out on disconnected" code was move from the function `__aexit__` to `disconnect`. The `disconnect` function is called inside a try/except block in the function `__aexit__`, which suppresses the disconnected exception. This results in that the context manager exits without exception also when there was a disconnect-exception.
Example:
- start mqtt broker
- run a similar code:
```python
async with Client("localhost") as client:
async with client.messages() as messages:
await client.subscribe("humidity/#")
async for message in messages:
print(message.payload)
```
- shutdown broker
expection: I get some sort of exception
actual: no exception, only a log entry.
This bug was found on the upgrade from `0.16.1` to `1.0.0`. Afterwards the following test was failing …
> don't suppress exception on aexit

- aiomqtt/client.py
Resolves #227 
Adds the `tls_insecure` kwarg to Client `__init__()`. If set, the value is forwarded directly to the Paho [`tls_insecure_set()`](https://eclipse.dev/paho/index.php?page=clients/python/docs/index.php#option-functions) function.
> feat: expose paho tls_insecure_set(bool)

- aiomqtt/client.py
- tests/test_client.py
If connection fails calling `__aexit__` will result in an Lock-exception.
This small check prevents that
> release lock only if acquired

- aiomqtt/client.py
- scripts/test
- tests/test_client.py
As previously discussed in #216, this deprecates calls to `connect` and `disconnect` in favor of `__aenter__` and `__aexit__`.
Hopefully, this will also [simplify the internal state](https://github.com/sbtinstruments/aiomqtt/pull/216#pullrequestreview-1434130633) in the future. On that matter, Frederik, could you elaborate on what you meant by "Have all internal state inside a tagged union (sum type) in rust-style, concurrency-safe semantics."?
> refactor: Deprecate connect and disconnect methods

- aiomqtt/__init__.py
- pyproject.toml
> fix: aiomqtt has no attribute __version__

- CHANGELOG.md
- aiomqtt/client.py
Because of the iterator construction in `__init__`, any attempt to iterate over `client.messages` after the initial iteration will yield no data.
Here's an MVP of the actual defect:
```py
import sys
import os
if sys.platform.lower() == "win32" or os.name.lower() == "nt":
from asyncio import set_event_loop_policy, WindowsSelectorEventLoopPolicy
set_event_loop_policy(WindowsSelectorEventLoopPolicy())
import asyncio
import aiomqtt
async def main():
async with aiomqtt.Client("test.mosquitto.org") as client:
async def listen():
async for message in client.messages:
print(message.payload)
listen_task = asyncio.create_task(listen())
await client.subscribe("temperature/#")
try:
await asyncio.wait_for(listen_task, timeout=0.5)
except asyncio.TimeoutError:
listen_task.cancel()
await listen()
raise …
```
> Fix: Iterating over received messages multiple times does not yield proper results

- CHANGELOG.md
- docs/alongside-fastapi-and-co.md
Update the doc example for integration with FastAPI to use FastAPI's dependency injection for the MQTT client
Closes https://github.com/sbtinstruments/aiomqtt/issues/320
> Update FastAPI doc to use dependency injection

- aiomqtt/client.py
- tests/test_client.py
> Replace messages generator with iterator class that implements len()

- aiomqtt/client.py
Hi, my name is William Pickard and I work for Toro Robotics Colorado.
We noticed that on subscription to topics with a retained message over TLS, the retained message for that topic is received after a considerable delay (seems to be until after the first keepalive).
A review of the `paho-mqtt` project turned up and older PR addressing this issue:
See: https://github.com/eclipse-paho/paho.mqtt.python/issues/131
This PR ports the above fix from `paho-mqtt` to the `aiomqtt` client.
Minimal steps to reproduce:
```python
import aiomqtt
import asyncio
from async_timeout import timeout
import ssl
HOSTNAME = 'test.mosquitto.org'
TOPIC = '/tests/aiomqtt/test_delayed_retain_ssl'
CONTEXT = ssl.create_default_context()
CONTEXT.check_hostname = False
CONTEXT.verify_mode = ssl.VerifyMode.CERT_NONE …
```
> Fix: retained message delayed on TLS connection

- aiomqtt/client.py
This allows `proxy_port` to be passed to the underlying paho `proxy_set()` function call according to [the Paho MQTT docs](https://eclipse.dev/paho/files/paho.mqtt.python/html/client.html#paho.mqtt.client.Client.proxy_set). Also addresses https://github.com/empicano/aiomqtt/issues/337
> Add Proxy Port Parameter

- CHANGELOG.md
- aiomqtt/message.py
- pyproject.toml
- tests/conftest.py
- uv.lock
This fixes the type hint for `Message.payload`, which was previously `PayloadType`.
Since `paho.mqtt.client.MQTTMessage.payload` is always `bytes`, the correct type should be `bytes`.
Closes #370
> Fix the type hint for Message.payload
